### ISSUE TITLE
Background image resizing issue

### ISSUE THREAD

**Issue by akshaybabloo** [timcreative/bootstrap-wizard#2]
Hi! When resizing the window, the background image doesn't cover completely at the bottom. 

<img width="399" alt="screen shot 2016-11-16 at 4 38 17 am" src="https://cloud.githubusercontent.com/assets/7360286/20311970/98db74ae-abb6-11e6-8cba-ae10a731ebba.png">

I would recommend the following:

1. Remove the inline style at `<div class="image-container set-full-height" style="background-image: url('assets/img/wizard.jpg')">`
2. And put a block style as 

```css
<style>
        body {
            background: url('assets/img/wizard.jpg') no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
</style>
```

It worked for me.
